/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Pr0miseAmbulanceWlList {
    }
}
declare global {
    interface HTMLPr0miseAmbulanceWlListElement extends Components.Pr0miseAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLPr0miseAmbulanceWlListElement: {
        prototype: HTMLPr0miseAmbulanceWlListElement;
        new (): HTMLPr0miseAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "pr0mise-ambulance-wl-list": HTMLPr0miseAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Pr0miseAmbulanceWlList {
    }
    interface IntrinsicElements {
        "pr0mise-ambulance-wl-list": Pr0miseAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pr0mise-ambulance-wl-list": LocalJSX.Pr0miseAmbulanceWlList & JSXBase.HTMLAttributes<HTMLPr0miseAmbulanceWlListElement>;
        }
    }
}
